version: '3.8'
services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=12345678
      - DATABASE_NAME=API
    depends_on:
      - db

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - back-end

  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: API
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
